enum class ErrorCode
{
    // Lexical Errors (L001-L099)
    L001_INVALID_CHARACTER,
    L002_UNTERMINATED_STRING,
    L003_INVALID_NUMBER_FORMAT,

    // Syntax Errors (S001-S099)
    S001_UNEXPECTED_TOKEN,
    S002_MISSING_EXPECTED_TOKEN, // e.g., missing semicolon
    S003_INVALID_EXPRESSION,
    S004_INVALID_STATEMENT,
    S005_INVALID_ASSIGNMENT_TARGET,

    // Type Errors (T001-T099)
    T001_TYPE_MISMATCH,
    T002_UNDEFINED_VARIABLE,
    T003_UNDEFINED_FUNCTION,
    T004_UNDEFINED_TYPE,
    T005_UNDEFINED_MEMBER, // For classes/structs
    T006_INVALID_OPERATOR_FOR_TYPE,
    T007_INCORRECT_ARGUMENT_COUNT,
    T008_INCORRECT_ARGUMENT_TYPE,
    T009_CANNOT_INFER_TYPE,
    T010_RETURN_TYPE_MISMATCH,

    // Semantic Errors (M001-M099) - More general meaning errors
    M001_DUPLICATE_DEFINITION,
    M002_INVALID_BREAK_CONTINUE, // Outside loop
    M003_INVALID_RETURN,         // Outside function
    M004_UNREACHABLE_CODE,       // Potentially a warning
    M005_UNUSED_VARIABLE,        // Potentially a warning
    M006_MODULE_NOT_FOUND,
    M007_CIRCULAR_DEPENDENCY,

    // Borrowing/Ownership errors (B001-B099)
    B001_USE_AFTER_MOVE,
    B002_BORROW_CONFLICT,
    B003_MUTABILITY_ERROR,
    B004_MOVE_BORROWED_VALUE,

    // Pattern matching errors (P001-P099)
    P001_NON_EXHAUSTIVE_PATTERNS,
    
    // FFI Errors (F001-F099)
    F001_FFI_CALL_FAILED,
    F002_FFI_TYPE_CONVERSION_ERROR,
    F003_FFI_SETUP_ERROR,

    // I/O Errors (I001-I099)
    I001_FILE_NOT_FOUND,
    I002_PERMISSION_DENIED,
    I003_READ_ERROR,
    I004_WRITE_ERROR,

    // Internal Compiler Errors (C001-C099) - Bugs in the compiler itself
    C001_UNIMPLEMENTED_FEATURE,
    C002_CODEGEN_ERROR,
    C003_TYPECHECK_ERROR, // Internal logic error
    C004_INTERNAL_ASSERTION_FAILED,

    // Generic/Unknown
    G001_UNKNOWN_ERROR,
    G002_GENERAL_SYNTAX_ERROR,
    G003_GENERAL_TYPE_ERROR,
    G004_GENERAL_SEMANTIC_ERROR,
}; 
